version: "3.8"

services:

  citas-service:
    build: ./services/citas-service
    ports:
      - "3001:3001"

  notificaciones-service:
    build: ./services/notificaciones-service
    ports:
      - "4000:4000"

  frontend:
    build: ./frontend
    ports:
      - "5173:5173"
    depends_on:
      - citas-service
      - notificaciones-service
